version: "3.8"

services:
  db:
    image: postgres:13.0-alpine
    env_file:
      - ./docker/db/.env
    ports:
      - 6543:5432
  flyway:
    image: flyway/flyway:7.2
    env_file:
      - ./docker/db/.env
    command: -configFiles=/flyway/conf/flyway.config -locations=filesystem:/flyway/sql -connectRetries=60 migrate
    volumes:
      - ./flyway/sql_versions:/flyway/sql
      - ./flyway/docker-flyway.config:/flyway/conf/flyway.config
    depends_on:
      - db
