version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
      - '/etc/localtime:/etc/localtime:ro'
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    image: hasura/graphql-engine:v1.3.3
    ports:
      - '8080:8080'
    depends_on:
      - 'postgres'
    restart: always
    env_file:
      - ./.env.hasura
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
volumes:
  db_data:
