version: "3.8"

services:
  core-api:
    image: docker.pkg.github.com/gmencz/gmc.sh/api.gmc.sh:latest
    networks:
      - traefik-net
      - gmc-sh-api-net
    env_file:
      - ./src/core-api/.env
      - ./src/core-api/prisma/.env
    labels:
      # Explicitly tell Traefik to expose this container
      - "traefik.enable=true"
      # The domain the service will respond to
      # The routers property has to match the container name (api-gabrielmendezc-com)
      - "traefik.http.routers.core-api.rule=Host(`api.gmc.sh`)"
      # Allow request only from the predefined entry point named "websecure"
      - "traefik.http.routers.core-api.entrypoints=websecure"
      - "traefik.http.routers.core-api.service=core-api-service"
      # Tell traefik to use the port 3000 to connect to this container
      - "traefik.http.services.core-api-service.loadbalancer.server.port=80"
      # Tell traefik to use the certificate resolver named "myresolver"
      - "traefik.http.routers.core-api.tls.certresolver=myresolver"
      # Redirect http to https
      - "traefik.http.middlewares.test-redirectscheme.redirectscheme.scheme=https"
      - "traefik.http.middlewares.test-redirectscheme.redirectscheme.permanent=true"
      - "traefik.docker.network=core_traefik-net"
  next-app:
    image: docker.pkg.github.com/gmencz/gmc.sh/app.gmc.sh:latest
    networks:
      - gmc-sh-web-net
  next-app-reverse-proxy:
    image: docker.pkg.github.com/gmencz/gmc.sh/app.gmc.sh-reverse-proxy:latest
    networks:
      - traefik-net
      - gmc-sh-web-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.next-app-reverse-proxy.rule=Host(`app.gmc.sh`)"
      - "traefik.http.routers.next-app-reverse-proxy.entrypoints=websecure"
      - "traefik.http.routers.next-app-reverse-proxy.service=next-app-reverse-proxy-service"
      - "traefik.http.services.next-app-reverse-proxy-service.loadbalancer.server.port=80"
      - "traefik.http.routers.next-app-reverse-proxy.tls.certresolver=myresolver"
      - "traefik.http.middlewares.test-redirectscheme.redirectscheme.scheme=https"
      - "traefik.http.middlewares.test-redirectscheme.redirectscheme.permanent=true"
      - "traefik.docker.network=core_traefik-net"

networks:
  traefik-net:
    external:
      name: core_traefik-net
  gmc-sh-api-net:
    external:
      name: gmc-sh-api-net
  gmc-sh-web-net:
    external:
      name: gmc-sh-web-net