name: Deploy
on:
  push:
    branches-ignore:
      - main
jobs:
  deploy:
    name: Deploy core API and Next app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14'
          
      - name: Publish core API docker image to Github Package Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: gmencz/gmc.sh/api.gmc.sh
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          dockerfile: Dockerfile.api
          tags: latest