name: Deploy
on:
  push:
    branches:
      - main
jobs:
  migrate-prod-db:
    name: Migrate production database
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14'
        
      - name: Install deps
        uses: bahmutov/npm-install@v1
      
      - name: Run migrations
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npx prisma migrate deploy --preview-feature