name: build

on:
  push:
    branches:
      - master

jobs:
  build-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: ./api
      - name: Publish to Github Package Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: gabrielmendezc/gmc.sh/api
          registry: docker.pkg.github.com
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
          workdir: ./api
          dockerfile: Dockerfile
          tags: latest
