name: Deploy
on:
  push:
    branches:
      - no-monorepo-vercel
jobs:
  migrate-prod-db:
    name: Migrate production database
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      
      - name: Run migrations
        run: |
          docker run --rm -e POSTGRES_HOST='${{ secrets.DB_HOST }}' \
          -e POSTGRES_PORT='${{ secrets.DB_PORT }}' \
          -e POSTGRES_DB='${{ secrets.DB_NAME }}' \
          -e POSTGRES_USER='${{ secrets.DB_USER }}' \
          -e POSTGRES_PASSWORD='${{ secrets.DB_PASSWORD }}' \
          -v `pwd`/flyway/sql_versions:/flyway/sql
          -v `pwd`/flyway:/flyway/conf \
          flyway/flyway migrate