name: Deploy
on:
  push:
    branches:
      - no-monorepo-vercel
jobs:
  migrate-prod-db:
    name: Migrate production database
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      
      - name: Run migrations
        env:
          POSTGRES_HOST: ${{ secrets.DB_HOST }}
          POSTGRES_PORT: ${{ secrets.DB_PORT }}
          POSTGRES_DB: ${{ secrets.DB_NAME }}
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: docker-compose -f docker-compose.prod.yml up -d