name: CI
on:
  push:
    branches-ignore:
      - main
jobs:
  build:
    name: Check types, lint, and test
    runs-on: ubuntu-latest
    env:
      SESSION_SECRET_PATH: session-secret-key
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14'
        
      - name: Install deps
        uses: bahmutov/npm-install@v1

      - name: Check types
        run: npm run check-types
      
      - name: Lint
        run: npm run lint

      - name: Test
        env:
          CI: true
          AUTH0_COOKIE_SECRET: ${{ secrets.AUTH0_COOKIE_SECRET }}
          AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
          AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
          AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
        run: npm run test:ci
      
      - name: Test E2E
        env:
          CI: true
          AUTH0_COOKIE_SECRET: ${{ secrets.AUTH0_COOKIE_SECRET }}
          AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
          AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
          AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
        run: npm run test:e2e:run