name: CI
on:
  push:
    branches-ignore:
      - main
jobs:
  build:
    name: Check types, lint, and test
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_AUTH0_DOMAIN: ${{ secrets.NEXT_PUBLIC_AUTH0_DOMAIN }}
      NEXT_PUBLIC_AUTH0_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_AUTH0_CLIENT_ID }}
      NEXT_PUBLIC_AUTH0_AUDIENCE: ${{ secrets.NEXT_PUBLIC_AUTH0_AUDIENCE }}
      NEXT_PUBLIC_GQL_ENDPOINT: ${{ secrets.NEXT_PUBLIC_GQL_ENDPOINT }}
      NEXT_PUBLIC_API_MOCKING: ${{ secrets.NEXT_PUBLIC_API_MOCKING }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Check types
        run: npm run check-types
      
      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test:ci