name: CI
on:
  push:
    branches-ignore:
      - main
jobs:
  build:
    name: Check types, lint, and test
    runs-on: ubuntu-latest
    env:
      SESSION_SECRET_PATH: session-secret-key
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14'
        
      - name: Install root deps
        uses: bahmutov/npm-install@v1

      - name: Install packages deps
        run: npm run clean-install

      - name: Build the stack
        run: |
          docker-compose -f docker-compose.test.yml up -d db_test
          docker-compose -f docker-compose.test.yml up flyway_test

      - name: Check types
        run: npm run check-types
      
      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test:ci
      - run: npm run test:e2e

        env:
          CI: true